version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # port 8080 tidak di-expose ke host secara langsung,
      # karena nanti akan diakses via Nginx proxy.
      - "8080:8080"
    volumes:
      - ./Backend/uploads:/app/uploads
    env_file:
      - ./Backend/.env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: portofolio_yeremia
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  nginx:
    image: nginx:alpine
    # Kita akan me-mount config file Nginx custom
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/yeremiapane.me/fullchain.pem:/etc/nginx/ssl/cert.pem:ro
      - /etc/letsencrypt/live/yeremiapane.me/privkey.pem:/etc/nginx/ssl/key.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always

volumes:
  db_data:
