version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Backend/uploads:/app/uploads
    env_file:
      - ./Backend/.env
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: portofolio_yeremia
    ports:
      - "3307:3306" # MySQL container menggunakan port 3306, dipetakan ke 3307 di host
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
